export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOAD_FEEDS = 'LOAD_FEEDS';
export const LOAD_FEEDS_SUCCESS = 'LOAD_FEEDS_SUCCESS';
export const LOAD_FEEDS_ERROR = 'FEEDS_LOADING_ERROR';
